# Copyright 2018 Canonical Ltd.
#
# This file is part of the SYSConfig Charm for Juju.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranties of
# MERCHANTABILITY, SATISFACTORY QUALITY, or FITNESS FOR A PARTICULAR
# PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
options:
  reservation: 
    type: string
    default: "off"
    description: |
        Type of CPU reservation: isolcpus, affinity, off
        isolcpus is a kernel cmdline paremeter
        affinity (CPU Affinity) is a systemd configuration parameter.
        Other processes inherit from systemd-system.conf
        off (default) disables any CPU reservation on host-side.
  cpu-range: 
    type: string
    default: ""
    description: |
        Single pcpus (0,1,2) or range of pcpus (0-10) to isolate (if
        isolcpus is selected) or reserve (if affinity is selected)
        .
        Default value (empty) will make "reservation" work as if it was
        "off".
  hugepagesz:
    type: string
    default: ""
    description: |
        Size of each hugepage. Example: 1G
  hugepages:
    type: string
    default: ""
    description: |
        Number of hugepages. Example: 448
  update-grub:
    type: boolean
    default: false
    description: | 
        Allows the charm to run "update-grub" command if
        /etc/default/grub was changed
        .
        This is discouraged and by default it is disabled.
  config-flags: 
    default: ""
    type: string 
    description: |
        If extra lines need to be configured on /etc/default/grub
        (isolcpus) or /etc/systemd/system.conf (affinity), this string
        can be used as a list in yaml format.
        Sample: |
           key1=value1
           key2=value2
  governor:
    type: string
    default: ""
    description: |
        Configured via cpufrequtils, possible values are powersave or
        performance
