[tool.flake8]
ignore = ["D100","D103"]
exclude = [".git", "__pycache__", ".tox", "charmhelpers", "mod", ".build"]
max-line-length = 88
max-complexity = 10

[tool.black]
exclude = '''
(
    \.eggs
  | \.git
  | \.tox
  | \.venv
  | \.build
  | dist
  | charmhelpers
  | mod
)/
'''
